### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by sdipietro** [j-corp-25/GlueTube#2]
# MVP List
- [x] Should have 7 Features.
  - [x] 3 of those are User Auth, Render, and Production README.
  - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points

**Comment by sdipietro** [comment]
Search should be a bonus feature. Should specify which feature contain full CRUD functionality

**Comment by j-corp-25** [comment]
Updated MVP list , let me know what you think. Added more details and specified the crud features more thoroughly

**Comment by j-corp-25** [comment]
added the checks

**Comment by sdipietro** [comment]
Subscriptions should be a bonus features

**Comment by j-corp-25** [comment]
thanks, updated on my end, now it looks like it aligns more with the 7 features, i hope i get to those bonuses
